# Generated by Django 4.1 on 2022-12-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestoreapp', '0012_user_ratings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_ratings',
        ),
    ]
